name: keeledger
description: "Keeledger - A zero-knowledge envelope-encrypted account and password manager."
publish_to: 'none'
version: 1.1.2+10

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: 2.3.2+1
  sqlite3_flutter_libs: ^0.5.42
  sqflite: ^2.4.2
  ota_update: ^7.1.0
  device_info_plus: ^12.4.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  path: ^1.9.1
  uuid: ^4.6.0
  window_manager: ^0.5.2
  csv: ^6.0.0
  intl: ^0.20.3
  lpinyin: ^2.0.3
  file_picker: ^10.3.10
  encrypt: ^5.0.3
  pointycastle: ^3.6.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  webdav_client: ^1.2.2
  flutter_markdown_plus: ^1.0.12

dependency_overrides:
  sqflite_common_ffi: 2.3.2+1
  sqlite3: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/docs/
